### ISSUE TITLE
sm_create error

### ISSUE THREAD

**Issue by kmarano-usgs** [usgs/shakemap#1108]
When using the -p (--preserve-params) argument with sm_create, it produces the following error:

Traceback (most recent call last):
  File "/home/shake/miniconda/envs/shakemap/bin/sm_create", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/shake/shakemap_src/bin/sm_create", line 542, in <module>
    main(pargs)
  File "/home/shake/shakemap_src/bin/sm_create", line 416, in main
    _write_model_conf(shakemap, module_conf, migrate_conf,
  File "/home/shake/shakemap_src/bin/sm_create", line 473, in _write_model_conf
    if bias_max_mag > 0 and max_range > 0:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by cbworden** [comment]
Thanks. I'll have a look.
